const propiedades = [
  {
    id: "2366",
    ref: "25-029-1",
    pais: "spain",
    tipo: "piso",
    zona: "Baixador",
    agente: "M&M .",
    banios: "1",
    ciudad: "Castelldefels",
    estado: "Disponible",
    estgen: "Necesita Reformas",
    moneda: "EUR",
    precio: "420000",
    puerta: "2",
    piscina: "1",
    m2constr: " 0",
    m2utiles: " 60",
    tipo_via: "Paseo",
    amueblado: "No",
    direccion: "Paseo Maritimo, 380, puerta 2A",
    emisiones: "0",
    m2terraza: " 0",
    nascensor: " 0",
    provincia: "Barcelona",
    situacion: "2da. Mano",
    ubicacion: "Area prestigiosa",
    fecha_alta: "2025-04-07 00:00:00",
    ntrasteros: " 0",
    num_planta: "1ª Planta",
    superficie: { plot: "0", built: "0" },
    alrededores:
      "Bus:\nParque Público:\nCampo de Fútbol:\nRestaurantes:\nAeropuerto:\nBuen acceso a carretera:\n",
    descripcion:
      "¡Oportunidad única! Piso a reformar en zona playa\nTe presentamos este piso de 60m2, ideal para quienes buscan personalizar su hogar o invertir en una ubicación privilegiada. \nSituado a pocos pasos de la playa, esta vivienda ofrece un enorme potencial para convertirla en el espacio de tus sueños.\nCaracterísticas principales:\nSuperficie: 60 m2 construidos.\n3 habitaciones: Espacios bien distribuidos, ideales para adaptarlos a tus necesidades.\n1 terraza privada: Perfecta para disfrutar del aire libre.\nTodo exterior: Con excelente entrada de luz natural durante todo el día.\nCon plaza de parking incluida. \nJardines comunitarios: Para disfrutar de momentos de relax rodeado de naturaleza.\nPiscina comunitaria: Un lugar ideal para refrescarte y pasar tiempo con familia o amigos.\nUbicado en una zona de playa, con acceso cercano a comercios, transporte público y servicios esenciales, \nesta propiedad combina comodidad y un entorno privilegiado.\n¡Perfecto para reformar y adaptar a tu gusto o como inversión!\nNo dejes pasar esta gran oportunidad. Contacta con nosotros para más información o para concertar una visita.\n¡Haz realidad tu proyecto en un entorno único!\n",
    dormitorios: "3",
    freq_precio: "sale",
    propietario: {
      codigo: "332",
      nombre: "Jacinto",
      apellido: "piso",
      comercial: "M&M .",
      fecha_alta: "12/02/2025 9:00:00",
    },
    num_inmueble: "380",
    num_terrazas: " 1",
    zonascomunes:
      "Piscina Comunitaria:\nBaloncesto:\nParque Infantil:\nJardines Comunitarios:\nCampo de Fútbol:\n",
    circunstancia: "Disponible",
    codigo_postal: "08860",
    tipo_operacion: "Venta",
    caracteristicas: [
      "Planta 1",
      "Aparcamiento",
      "Terraza",
      "Jardin",
      "2da. Mano",
      "Necesita Reformas",
      "Comunidad:  0",
      "Ubicación: Area prestigiosa",
      "Orientación: Buena",
    ],
    consumo_energia: "0",
    des_orientacion: "Buena",
    geolocalizacion: { latitude: "41.264896", longitude: "1.947701" },
    num_pisos_bloque: "0",
    construccion_nueva: "0",
    num_pisos_edificio: "0",
  },
  {
    id: "2378",
    ref: "25-001-1",
    pais: "spain",
    tipo: "piso",
    zona: "Baixador",
    agente: "M&M .",
    banios: "1",
    ciudad: "Castelldefels",
    cocina: "Independiente - Amueblada con elec.",
    estado: "Disponible",
    estgen: "Buen Estado",
    moneda: "EUR",
    precio: "410000",
    puerta: "14",
    piscina: "0",
    ventana: "Aluminio",
    m2constr: " 66",
    m2utiles: " 60",
    tipo_via: "Paseo",
    amueblado: "Semi Amueblado",
    direccion: "Paseo Del Ferrocarril, 10, puerta 14",
    emisiones: "0",
    nascensor: " 0",
    provincia: "Barcelona",
    situacion: "2da. Mano",
    ubicacion: "Buena Situación",
    fecha_alta: "2025-03-29 00:00:00",
    ntrasteros: " 0",
    num_planta: "Bajo",
    superficie: { plot: "0", built: "66" },
    tipo_suelo: "Parquet",
    descripcion:
      "Preciosa planta baja reformada en la zona de Baixador\nOportunidad única de adquirir una vivienda de 60 m2 totalmente reformada, ubicada a tan solo 5 minutos de la playa y cerca del transporte público.\nLa propiedad cuenta con:\n2 habitaciones: 1 doble y 1 individual, ideales para parejas o familias pequeñas.\nCocina americana: Totalmente equipada, abierta al salón, lo que ofrece un espacio amplio y luminoso.\nTerraza privada de 12 m2: Perfecta para disfrutar del aire libre y el buen clima de la zona.\nParking incluido: Una comodidad adicional en la zona.\nEquipamiento completo: Calefacción, aire acondicionado, listos para entrar a vivir.\nUna vivienda ideal tanto como residencia habitual, como inversión para alquilar gracias a su excelente ubicación cerca del mar.\n",
    dormitorios: "2",
    freq_precio: "sale",
    propietario: {
      codigo: "344",
      nombre: "Vero",
      apellido: "Kamala",
      comercial: "M&M .",
      fecha_alta: "14/02/2025 9:00:00",
    },
    num_inmueble: "10",
    num_terrazas: " 1",
    circunstancia: "Disponible",
    climatizacion: "a/a f/c",
    codigo_postal: "08860",
    tipo_operacion: "Venta",
    caracteristicas: [
      "Bajo",
      "Aparcamiento",
      "Terraza",
      "2da. Mano",
      "Buen Estado",
      "Comunidad:  0",
      "Suelo: Parquet",
      "Climatización: a/a f/c",
      "Ventanas: Aluminio",
      "Cocina: Independiente - Amueblada con elec.",
      "Ubicación: Buena Situación",
      "Orientación: Buena",
    ],
    consumo_energia: "0",
    des_orientacion: "Buena",
    geolocalizacion: { latitude: "41.265858", longitude: "1.952578" },
    num_pisos_bloque: "0",
    construccion_nueva: "0",
    num_pisos_edificio: "0",
  },
  // ... (agregá aquí los otros 3 registros siguiendo el mismo formato)
];
